### PR TITLE
GTK4+libadwaita port, many layout fixes, etc

### LINKED ISSUE #26: Lack of free space in header
* Wordbook version: 0.3.1 (flatpak)
* Operating System: debian 11
* Desktop Environment: Gnome 3.38.5

### Description

The Wordbooks's window header is always fully filled with buttons and search bar, even maximized. Such header is used to drag windows (at least in Gnome 3.XX). So to drag Wordbook window i have to use a little space between elements in header, which is not so easy. Can you fix this with adding some free space into header? My suggestions are to disable auto width of search bar or to add some padding. You can also make use of free header space by adding the centered name of your app there.

Screenshot from 2021-09-20 21-34-36

### PR DESCRIPTION
**Pull request by fushinari**
Closes #26

### CODE REVIEW

**Comment by fushinari** [comment]
To-do:
- [ ] Improve history
- [ ] Specify supported language
- [ ] Increase preferences window default width
- [ ] Tooltips for HeaderBar buttons
- [ ] Tooltip for pronunciation button
- [ ] Scrollbar anchor to right
- [ ] i18n support
- [ ] Clamp search bar width

Unsure about:
- [ ] Remove search button and default to live search
- [ ]

**Comment by fushinari** [comment]
Other work:

- [ ] Improve project structure
- [ ] Use devel builds by default
- [ ] Use GLib where necessary
- [ ] Improve documentation, both within code and outside
- [ ] Make custom definitions more obscure
- [ ] Less and less hardcoding
- [ ] Improve strings where possible
- [ ] Fix completions only being shown when there is at least 10 available completions. Also prepare completions for migration to GTK4.
- [ ] Complete work on restructuring how results are formed.

**Comment by fushinari** [comment]
Defaulting to live search is troublesome because then the matter of how and when to present completions comes up. So that needs some additional thought.

**Comment by sophie-h** [comment]
@fushinari feel free to join `#app-dev:gnome.org` on Matrix if you need help with porting your app or want feedback for design decisions :)

**Comment by fushinari** [comment]
Joined! Thanks for letting me know! :)

**Comment by fushinari** [comment]
What's still broken (GTK4):
- **Zombie process**: `wordbook` leaves a zombie process if `GLib.idle_add(self._search_entry.grab_focus)` is called during its runtime. Haven't found a workaround yet.
- **Completions**: `actions` seem to be gone from GTK4. I can't ~ab~use them anymore. Either remove completions and replace with another mechanism, or find a way to give a custom list to `EntryCompletion`.
- **Double click to search**: I haven't looked into it enough.
- **Type to search**: (i.e. type anywhere, without the searchentry needing to be focused). Should be possible if using `GtkEntry`. But using `GtkEntry` has led to issues, so will need to look into it.

**Pull request merged**
